// Shared icon names used across web and mobile
export const ICON_NAMES = {
  plans: 'map',
  tasks: 'check-square',
  photos: 'camera',
  forms: 'clipboard',
  reports: 'bar-chart-2',
  documents: 'file-text',
  settings: 'settings',
  notifications: 'bell',
  search: 'search',
  plus: 'plus',
  edit: 'edit-2',
  delete: 'trash-2',
  filter: 'filter',
  sort: 'arrow-up-down',
  calendar: 'calendar',
  user: 'user',
  users: 'users',
  building: 'building',
  pin: 'map-pin',
  comment: 'message-square',
  attachment: 'paperclip',
  download: 'download',
  upload: 'upload',
  close: 'x',
  menu: 'menu',
  chevronRight: 'chevron-right',
  chevronDown: 'chevron-down',
} as const;
